# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    AppBundle\Foo:
        public: false

    dummy:
        class: AppBundle\Foo
        arguments:
            - '@AppBundle\Foo'

    another_dummy:
        class: AppBundle\Foo
        arguments:
            - '@AppBundle\Foo'
